/**
 * Auto-detects the machine's local WiFi IP and writes it to src/api/host.ts
 * so the physical Android device can reach the dev backend over the same network.
 *
 * Run: node scripts/get-ip.js
 */

const { networkInterfaces } = require('os');
const fs = require('fs');
const path = require('path');

function getLocalIP() {
  const nets = networkInterfaces();
  for (const name of Object.keys(nets)) {
    // Prefer WiFi / WLAN interfaces
    const isWifi = /wi-?fi|wlan|en0|en1/i.test(name);
    for (const net of nets[name]) {
      if (net.family === 'IPv4' && !net.internal) {
        if (isWifi) return net.address;
      }
    }
  }
  // Fallback: first non-internal IPv4
  for (const nets2 of Object.values(networkInterfaces())) {
    for (const net of nets2) {
      if (net.family === 'IPv4' && !net.internal) return net.address;
    }
  }
  return '127.0.0.1';
}

const ip = getLocalIP();
const outPath = path.join(__dirname, '..', 'src', 'api', 'host.ts');

const content = `// AUTO-GENERATED by scripts/get-ip.js — do not edit manually
// Re-run "npm run android" to refresh if your IP changes.
export const DEV_HOST = '${ip}';
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(`✅  Dev host set to: http://${ip}:3000`);
