import axios, { AxiosInstance, InternalAxiosRequestConfig } from 'axios';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { DEV_HOST } from './host';
import type { RetryableConfig } from '../types/client.types';

// host.ts is auto-generated by "npm run android" (scripts/get-ip.js)
// For production replace with your real API domain.
export const API_BASE = __DEV__
  ? `http://${DEV_HOST}:3000/api/v1`
  : 'https://api.yourdomain.com/api/v1';

export const STORAGE_KEYS = {
  ACCESS_TOKEN: '@hh_access_token',
  REFRESH_TOKEN: '@hh_refresh_token',
  USER: '@hh_user',
  // Stable per-install identifier for push device-token registration. Generated
  // once, persisted; survives FCM token rotation and is sent on logout cleanup.
  DEVICE_ID: '@hh_device_id',
};

let refreshInFlight: Promise<string | null> | null = null;

export const api: AxiosInstance = axios.create({
  baseURL: API_BASE,
  timeout: 15000,
  headers: { 'Content-Type': 'application/json' },
});

// Attach access token to every request
api.interceptors.request.use(async (config: InternalAxiosRequestConfig) => {
  const token = await AsyncStorage.getItem(STORAGE_KEYS.ACCESS_TOKEN);
  if (token && config.headers) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Auto-refresh on 401
api.interceptors.response.use(
  (res) => res,
  async (error) => {
    const original = error.config as RetryableConfig;
    if (error.response?.status === 401 && !original._retry) {
      original._retry = true;
      try {
        const newToken = await refreshAccessToken();
        if (newToken && original.headers) {
          original.headers.Authorization = `Bearer ${newToken}`;
          return api(original);
        }
      } catch {
        await clearTokens();
      }
    }
    return Promise.reject(error);
  },
);

async function refreshAccessToken(): Promise<string | null> {
  if (refreshInFlight) return refreshInFlight;

  refreshInFlight = (async () => {
    try {
      const refreshToken = await AsyncStorage.getItem(STORAGE_KEYS.REFRESH_TOKEN);
      if (!refreshToken) return null;

      const { data } = await axios.post<{
        success: true;
        data: { accessToken: string; refreshToken?: string; expiresIn: number };
      }>(`${API_BASE}/auth/refresh`, { refreshToken }, {
        headers: { Authorization: `Bearer ${refreshToken}` },
      });

      const newToken = data.data.accessToken;
      // The backend rotates the refresh token on every refresh — persist the new
      // one so the next refresh doesn't send a revoked token.
      const writes: Record<string, string> = { [STORAGE_KEYS.ACCESS_TOKEN]: newToken };
      if (data.data.refreshToken) {
        writes[STORAGE_KEYS.REFRESH_TOKEN] = data.data.refreshToken;
      }
      await AsyncStorage.setMany(writes);
      return newToken;
    } catch {
      return null;
    } finally {
      refreshInFlight = null;
    }
  })();

  return refreshInFlight;
}

export async function clearTokens(): Promise<void> {
  await Promise.all([
    AsyncStorage.removeItem(STORAGE_KEYS.ACCESS_TOKEN),
    AsyncStorage.removeItem(STORAGE_KEYS.REFRESH_TOKEN),
    AsyncStorage.removeItem(STORAGE_KEYS.USER),
  ]);
}

export function extractApiError(err: unknown): string {
  if (axios.isAxiosError(err)) {
    return (err.response?.data as { error?: { message?: string } })?.error?.message
      ?? err.message;
  }
  return 'Something went wrong';
}
