export const API = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    ME: '/users/me',
    PATIENTS: '/users/patients',
    PATIENT_BY_ID: (id: string): string => `/users/patients/${id}`,
    ADDRESSES: '/users/addresses',
    ADDRESS_BY_ID: (id: string): string => `/users/addresses/${id}`,
  },
  SERVICE_TYPES: '/service-types',
  PACKAGES: '/packages',
  CITIES: '/cities',
  STAFF: {
    LIST: '/staff',
    ME: '/staff/me',
    MY_PROFILE: '/staff/me/profile',
    MY_AVATAR: '/staff/me/avatar',
    BY_ID: (id: string): string => `/staff/${id}`,
    VERIFY: (id: string): string => `/staff/${id}/verify`,
    AVAILABILITY: (id: string): string => `/staff/${id}/availability`,
    DOCS: (id: string): string => `/staff/${id}/documents`,
    DOC_PRESIGN: (id: string): string => `/staff/${id}/documents/presign`,
    DOC_CONFIRM: (id: string): string => `/staff/${id}/documents/confirm`,
    DOC_REVIEW: (id: string, docId: string): string => `/staff/${id}/documents/${docId}`,
    SERVICES: (id: string): string => `/staff/${id}/services`,
    SERVICE_REMOVE: (id: string, svcId: string): string => `/staff/${id}/services/${svcId}`,
  },
  BOOKINGS: {
    LIST: '/bookings',
    BY_ID: (id: string): string => `/bookings/${id}`,
    CONFIRM: (id: string): string => `/bookings/${id}/confirm`,
    CANCEL: (id: string): string => `/bookings/${id}/cancel`,
    RESCHEDULE: (id: string): string => `/bookings/${id}/reschedule`,
    ASSIGN: (id: string): string => `/bookings/${id}/assignments`,
    VISITS: (id: string): string => `/bookings/${id}/visits`,
  },
  VISITS: {
    LIST: '/visits',
    BY_ID: (id: string): string => `/visits/${id}`,
    EN_ROUTE: (id: string): string => `/visits/${id}/en-route`,
    CHECK_IN: (id: string): string => `/visits/${id}/check-in`,
    CHECK_OUT: (id: string): string => `/visits/${id}/check-out`,
    COMPLETE: (id: string): string => `/visits/${id}/complete`,
    MISS: (id: string): string => `/visits/${id}/miss`,
    CANCEL: (id: string): string => `/visits/${id}/cancel`,
  },
  REPORTS: {
    LIST: '/reports',
    BY_ID: (id: string): string => `/reports/${id}`,
    PRESIGN: (id: string): string => `/reports/${id}/files/presign`,
    CONFIRM: (id: string): string => `/reports/${id}/files/confirm`,
    DELETE_FILE: (id: string, fileId: string): string => `/reports/${id}/files/${fileId}`,
  },
  REVIEWS: '/reviews',
  NOTIFICATIONS: '/notifications',
  ADMIN: {
    DASHBOARD: '/admin/dashboard/summary',
    STAFF_UTIL: '/admin/dashboard/staff-util',
    AUDIT_LOGS: '/admin/audit-logs',
    NOTIFICATION_RETRY: (id: string): string => `/admin/notifications/${id}/retry`,
  },
  PAYMENTS: {
    CREATE_INTENT: '/payments/create-intent',
  },
} as const;
